$ANSIBLE_VAULT;1.1;AES256
39376266343264353031626637336135313265303335636263393266623038663134343139336130
6262383263663630636231373263653038616339306437630a653436626362363830303137626564
65323337363532616638313436303565336162646563636332626633393633346665336535383830
6532363339343464340a363265356133303336343737646262333837386538373632333238316336
61323862646638643361663134383836343065383662313964363035306562393433656438663862
66646233383461636431626238623130646339633234666365633838656135326333343134396639
37333735613562313638653038316437333535646433356539653235393936306339646632373566
63656662386261613638
